### ISSUE TITLE
Hostname not showing properly

### ISSUE THREAD

**Issue by mister2d** [botleg/swarm-monitoring#6]
Any ideas on how to get the host and container name to show up correctly?

My single node test host shows up as "nmhmh0azbbaa8yfmdsvhzzit5" in Grafana.

I followed the instructions verbatim. Thanks!

**Comment by srihas619** [comment]
`show tag values with key = "container_name" WHERE machine =~ /^$host$/` OR `show tag values with key = "machine"` 
I think one of these query statements in _templating_ has to be altered to get the names in "view" as expected; I am new to grafana/influx. Please correct me if I am wrong.

**Comment by mister2d** [comment]
I'll get this tested later today.

**Comment by hanzeljesheen** [comment]
In the article, we have set the hostname for `cAdvisor` containers with `{{.Node.ID}}`. This sets the Docker Swarm `Node ID` for that node as the hostname. When `cAdvisor` sends the metrics collected for a host, it tags it with this hostname. So, the host for the metrics sent will be the `Node ID` of that host.
You can see the host corresponding to the ID with the command, `docker node ls`. If you are using a single node setup, you can replace `'{{.Node.ID}}'` in line 30 of `docker-stack.yml` to any name you want and that will be seen as the host.

**Comment by mister2d** [comment]
Thanks. I was able to verify this.

Unfortunately, I will need the hostname to dynamically set as the FQDN. The Node ID will be unusable when I deploy this at scale.

**Comment by srihas619** [comment]
@hanzeljesheen thank you,
 is there a way to check the cAdvisor's UI as well?

**Comment by mister2d** [comment]
@hanzeljesheen Hi again. I'm just revisiting the question.

What is the reason for using node.id again versus using node.hostname? If you use node.id in a swarm, how do you correlate that cryptic ID with the hostname?

**Comment by hanzeljesheen** [comment]
@mister2d There is currently no option to set the hostname of the container with that of its host. You only have the `{{.Node.ID}}` option, which gives the host's ID. You would need to correlate it with the hostname with the `docker node ls` command. You can see more about service templates [here](https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates).

@srihas619 you can see cAdvisor's UI by publishing the port 8080 of the `cAdvisor` container. Due to the Router Mesh feature of docker swarm mode, all the instances on the cAdvisor will share the port published. You can find more this [here](https://docs.docker.com/engine/swarm/ingress/). If you add the following lines to cadvisor block in `docker-stack.yml` file, you can publish it.
``` yml
ports:
  - 127.0.0.1:8080:8080
```
Now, if you go to port 8080 of any host in the swarm, you will be routed to any one of the cAdvisor instance. So, you might have to refresh the page a few times to get the right host.

**Comment by presto9292** [comment]
Support for {{.Node.Hostname}} was added in docker 17.10
https://github.com/docker/swarmkit/issues/1951

**Comment by hanzeljesheen** [comment]
Yes, you can now use `hostname: '{{.Node.Hostname}}'` instead of `hostname: {{.Node.ID}}` in `docker-stack.yml`. This will give the correct hostnames.
<img width="714" alt="hostnames" src="https://user-images.githubusercontent.com/2674768/33219066-571a019e-d166-11e7-9f01-66f730f9bc72.png">

**Comment by mister2d** [comment]
Very nice. I'll wait for 17.10 to be released.

**Comment by hanzeljesheen** [comment]
I've updated the repo and blog post to reflect this change. Check [here](https://botleg.com/stories/monitoring-docker-swarm-with-cadvisor-influxdb-and-grafana/) and [here](https://github.com/botleg/swarm-monitoring/blob/master/docker-stack.yml).
